### ISSUE TITLE
fatal: reference is not a tree

### ISSUE THREAD

**Issue by danshu** [walaj/bxtools#1]
Hi,

When I try to install this tool, I was not able to clone some submodules.

git clone --recursive https://github.com/walaj/bxtools.git
The error message is as following:

"Cloning into 'bxtools'...
remote: Counting objects: 69, done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 69 (delta 28), reused 69 (delta 28), pack-reused 0
Unpacking objects: 100% (69/69), done.
Checking connectivity... done.
Submodule 'SeqLib' (https://github.com/walaj/SeqLib.git) registered for path 'SeqLib'
Cloning into 'SeqLib'...
remote: Counting objects: 5188, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 5188 (delta 0), reused 0 (delta 0), pack-reused 5182
Receiving objects: 100% (5188/5188), 11.63 MiB | 1.08 MiB/s, done.
Resolving deltas: 100% (3140/3140), done.
Checking connectivity... done.
fatal: reference is not a tree: 58aa22093443f5de38e78170c4c73390e3df51e8
Unable to checkout '58aa22093443f5de38e78170c4c73390e3df51e8' in submodule path 'SeqLib'"

Best,
Danshu

**Comment by walaj** [comment]
Hi Danshu,

Thanks for letting me know, looks like the refactor in SeqLib broke the link here. I just fixed it now, and was able to clone and build on OSX. Let me know if any other issues.

Best,
Jeremiah

**Comment by danshu** [comment]
Hi Jeremiah,

Thanks! It works now!

Best,
Danshu
