### ISSUE TITLE
fail to open new bam file when splitting

### ISSUE THREAD

**Issue by verne91** [walaj/bxtools#15]
I want to split bam file with 10x barcodes. But it seemed that bxtools did not generate bam files for all barcodes. The error is "E::hts_open_format] fail to open file 'abc.bam'   Could not open BAM: abc.bam"

**Comment by walaj** [comment]
abc.bam is the BAM that you would like to split? Can you check that ``samtools`` can operate on this BAM? This looks like something is corrupted with the BAM, since the error is direct from htslib code that is baked into ``bxtools``.

**Comment by verne91** [comment]
I got the reason.
There are too many barcodes in the bam file and my system has the limitation of the number of opening files.

Thanks.
