### ISSUE TITLE
error in bxtools convert

### ISSUE THREAD

**Issue by verne91** [walaj/bxtools#17]
Hello,

I used the following command to sort the bam file by 'BX' tag. 
`bxtools convert $bam -v -k | samtools sort - -o bx_sorted.bam`

But I got an error after running about 30 mins.

```
.....
...at read 853,000,000 at pos 0:-1(+)
...at read 854,000,000 at pos 0:-1(+)
...starting second pass to flip chr and BX
terminate called after throwing an instance of 'std::out_of_range'
  what():  BamHeader::IDtoName - Requested ID is higher than number of sequences
```

**Comment by walaj** [comment]
For some reason, it is having a hard time with unmapped reads. A workaround
would be to filter these out with samtools and pipe the filtered reads into
bxtools. Not a great permanent solutions. @tkamath1, do you know what is
going on here?

**Comment by tkamath1** [comment]
Hi @verne91, thanks for bringing this up. Unfortunately I agree this may be an issue with unmapped reads. Another solution would be to drop tags when converting your BAM file (i.e. don't add the -k/keep-tags option when running convert). Hopefully this will resolve the issue albeit not being the perfect solution.

**Comment by verne91** [comment]
Hello @tkamath1 , thank you for your suggestion. But the purpose I use this program is getting a sorted bam file and then I can get the fragments for each barcode. If I don't keep the tags of chromosomes. I will lose the coordinates. Do you have any idea for my problem?

**Comment by walaj** [comment]
Right, you'll definitely need the tags. This is a bug in "convert",
although it may take me a few days to address. @tkamath1, are you able to
see where the bug is?

**Comment by tcashby** [comment]
Any updates on this? I'm encountering the same issue.

**Comment by walaj** [comment]
Thank you for your long patience with this. I have fixed this issue with the latest commit and ``convert`` is now working.
