### ISSUE TITLE
Problems with the "mol" module - reading in MI tag.

### ISSUE THREAD

**Issue by evolgenomics** [walaj/bxtools#18]
Many thanks for this otherwise very capable tool. Helps a lot with handling 10X data.

I have a question regarding the "mol" module. I'm getting messages suggesting that it can't read the MI tag of any of the BAM files I've got. I've mainly tried reading in file generated from mice. but also other organisms.

The message I got was:

****1e5 reads in and haven't hit MI tag yet****
****1e6 reads in and haven't hit MI tag yet****

This is from BXLOOPCHECK from bxcommon.h. But the main issue seems to be reading in the MI tag, which led me to look into SeqLib - but I haven't isolated the issue yet.

This was run on an Ubuntu-16.04 x86-64 system. Tried also on an Mac OSX and got the same result.

I include here an example line of the actual BAM file I used.

ST-J00101:68:HKHWYBBXX:2:1202:22242:1455        83      1       4347597 60      127M    =       4347178 -546    TAATGAACCTGGTATTTGAGAAATTCCATTCTGATGTTTCTGATTATTAGGAACAAAAGCTTCCAGGTGCCGTAGCAACAAGGCTGGTAAGTAGTCTTTTAGAACATTTTCTCCCATAGTATCTACC AJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ  DM:Z:0.250000   QT:Z:AAFFFJJJ   BC:Z:AAGATCAT   QX:Z:AAFFFJJJJJJJJJJJ   AM:A:1  XM:A:0  TR:Z:TATCACA    TQ:Z:JJJJJJJ    AS:f:-2 XS:f:-72.3669   BX:Z:TCGGTAAGTAGTTGTC-1 XT:i:0  RX:Z:TCGGTAAGTAGTTGTC   OM:i:60 RG:Z:CTRL-DMSO:LibraryNotSpecified:1:unknown_fc:0       PS:i:4240224    HP:i:1  PC:i:39 MI:i:50195

So there're definitely MI tags in the file. But they somehow just couldn't be read. Otherwise it generates no output. 

A stack trace gave me the following:

munmap(0x7f3e6933d000, 790528)          = 0
munmap(0x7f3e693fe000, 397312)          = 0
munmap(0x7f3e692dc000, 397312)          = 0
munmap(0x7f3e680b1000, 397312)          = 0
munmap(0x7f3e68050000, 397312)          = 0
munmap(0x7f3e67fef000, 397312)          = 0
munmap(0x7f3e67f8e000, 397312)          = 0
munmap(0x7f3e67f2d000, 397312)          = 0
munmap(0x7f3e67ecc000, 397312)          = 0
munmap(0x7f3e6945f000, 200704)          = 0
munmap(0x7f3e67e9b000, 200704)          = 0
munmap(0x7f3e67e09000, 397312)          = 0
munmap(0x7f3e67da8000, 397312)          = 0
munmap(0x7f3e67d47000, 397312)          = 0
munmap(0x7f3e67ce6000, 397312)          = 0
munmap(0x7f3e67c85000, 397312)          = 0
munmap(0x7f3e67c24000, 397312)          = 0
munmap(0x7f3e67bc3000, 397312)          = 0
munmap(0x7f3e67b62000, 397312)          = 0
munmap(0x7f3e67b01000, 397312)          = 0
munmap(0x7f3e67e6a000, 200704)          = 0
close(3)                                = 0
write(1, "ATATAGTTAGCAAATTACACTCCACAGACCCA"..., 453) = 453
fsync(1)                                = -1 EINVAL (Invalid argument)
close(1)                                = 0
brk(0x1017000)                          = 0x1017000
exit_group(0)                           = ?
+++ exited with 0 +++

I also tried substituting the SeqLib submodule with the master branch, which led to basically the same outcome, but now with segmentation fault.

.
.
.
munmap(0x7f0c01602000, 200704)          = 0
close(3)                                = 0
write(1, "ATATAGTTAGCAAATTACACTCCACAGACCCA"..., 453) = 453
fsync(1)                                = -1 EINVAL (Invalid argument)
close(1)                                = 0
brk(0xd37000)                           = 0xd37000
exit_group(0)                           = ?
+++ exited with 0 +++
Segmentation fault

I've also tried going back to an earlier commit right after the "mol" module was included, but I had the same results.

I've substituted several different 10X-derived BAM files and they all gave me the same outcome.

Any suggestions? I can send the bam file by FTP separately.
Thanks,
Frank

**Comment by walaj** [comment]
Thank you for the very detailed error report. There was indeed a bug in SeqLib, and I have updated bxtools to patch this. You will need to update the SeqLib submodule as well. 

Let me know if any issues with this patch.

**Comment by evolgenomics** [comment]
Thanks! Looks like that fixes it. Issue closed.
