### ISSUE TITLE
Name of this package/tool: bxtools or "snowman"?

### ISSUE THREAD

**Issue by brainstorm** [walaj/bxtools#22]
I guess this was an easter egg? Found it!

```
$ bxtools
Program: bxtools  <-------------------- OK
Contact: Jeremiah Wala [ jwala@broadinstitute.org ]
Usage: snowman <command> [options]   <-------------------- WHAT?

Commands:
(...)
```

While I'm here, could you please [create release(s)](https://help.github.com/articles/creating-releases/) for your software? It helps quite a lot [while packaging](https://github.com/bioconda/bioconda-recipes/pull/8205) and keeping track of versions/changes/bugs/etc...

**Comment by walaj** [comment]
Haha good catch. Copied a file over as a template from another project, looks like that stuck.

Awesome work with the bioconda packaging. I'll make a release today. I'll tag new releases when I get back to updating this project.
