### ISSUE TITLE
another installation error

### ISSUE THREAD

**Issue by seunghun23** [walaj/bxtools#23]
Hello,

While I was trying to install bxtools, I got following error 

```
/broad/software/free/Linux/redhat_6_x86_64/pkgs/gcc_5.2.0/bin/ld:
 /broad/software/free/Linux/redhat_6_x86_64/pkgs/bzip2_1.0.6/lib/libbz2.a(bzlib.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/broad/software/free/Linux/redhat_6_x86_64/pkgs/bzip2_1.0.6/lib/libbz2.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

```
Could you help me on this? 
Thank you for your help in advance!

-Seunghun

**Comment by walaj** [comment]
Hi Seunghun,
I see you are compiling on the Broad servers, is this correct? Will be helpful for easier debugging (since I have access to Broad servers).

**Comment by seunghun23** [comment]
Hi Jeremiah,

Thank you for contacting. I was going to email you, too.
I am a rotation student in Dr. Meyerson's lab working with Jian and Gavin,
and they recommended that I contact you.
Yes, I am trying to compile it on R2D2 broad server. I would really
appreciate it if you could help me fixing this

Best,
Seunghun

**Comment by walaj** [comment]
Hi Seungun,
Ah, makes sense. Since this is a Broad-specific issue, I'll close this and we can talk via email.
