### ISSUE TITLE
Split by HP tag including unphased reads? [Feature request]

### ISSUE THREAD

**Issue by lkhilton** [walaj/bxtools#26]
For the purposes of easily viewing coverage across the haplotypes, I split my longranger bams by haplotype. bxtools can create bam files for phased reads - is it possible to also output the unphased reads when -t HP is used? Something like an option to output to a single BAM file all the reads that don't match the specified tag would be great.

**Comment by walaj** [comment]
Do you mean reads with no HP tag? I can include that in the next update. In the meantime, a two-pass solution using grep + samtools to get these would also work.

**Comment by lkhilton** [comment]
Yes, that's what I mean - reads with no HP tag. I'm currently using the samtools + grep solution, but bxtools is definitely faster.

**Comment by walaj** [comment]
Thank you for your patience with this. 

I just pushed an update to ``bxtools split`` that allows for a ``-e`` flag to output a BAM with the reads without the specified tag.

**Comment by walaj** [comment]
Will close for now, but re-open if you have issues. On my tests this works well.

**Comment by jahanshah** [comment]
Thank you for your fantastic tool.
Unfortunately, bxtools split -e doesn't work for me!
