### ISSUE TITLE
Bed file of molecule extents

### ISSUE THREAD

**Issue by sjackman** [walaj/bxtools#3]
I'd like to create a BED file of molecule extents. For each unique molecule identifier (MI), create a bed file with the barcode (BX) and molecule (MI) and start and stop coordinate of each molecule. I then plan to use `bedtools` to calculate the depth of physical molecule coverage, and look for gaps in physical coverage.

**Comment by walaj** [comment]
Ah yes, I had seen this request come by Twitter, thanks for the reminder here. I know @cwhelan had a solution for this, and maybe he has suggestions for a different approach. I added just now the ``mol`` module, which I believe now does what you need (screenshot below from the output BED from a test BAM). Let me know if issues / other suggestions. 

Note that to update, you have to also update the SeqLib sub-repos as well after the git pull: git submodule update --recursive

![image](https://cloud.githubusercontent.com/assets/6922120/22740651/8a9b361c-edde-11e6-8c76-3b67a555ccf2.png)

**Comment by sjackman** [comment]
Thanks, Jeremiah! I'll check it out.
