### ISSUE TITLE
split, stats, tile with no arguments segfaults

### ISSUE THREAD

**Issue by sjackman** [walaj/bxtools#8]
`relabel` and `mol` with no arguments print useful `--help` text. `split`, `stats`, and `tile` segfault.

```
❯❯❯ src/bxtools split
[1]    64359 segmentation fault  src/bxtools split
```

`mol` accepts `--help` as an option, but none of the other tools do. Please consider adding a `--help` option to each tool.

**Comment by walaj** [comment]
Good catch. Fixed in next commit.

**Comment by sjackman** [comment]
Thanks, Jeremiah.
