### ISSUE TITLE
stats: Add median alignment score [feature request]

### ISSUE THREAD

**Issue by sjackman** [walaj/bxtools#9]
Please consider adding the median alignments score `AS` to the output of `stats`. Note that most tools like BWA output `AS:i` whereas Long Ranger align outputs `AS:f`.

**Comment by walaj** [comment]
Done. I can't figure out how (or even if possible) to infer tag type, so it is an input parameter:

e.g.
``bxtools stats $bam -A f``

**Comment by sjackman** [comment]
Thanks, Jeremiah! I opened PR #13 to use `AS:i` if it's present and otherwise `AS:f`.
